# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-31 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortinfo', models.CharField(max_length=30, verbose_name='文章简介')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('info', models.TextField(verbose_name='文章内容')),
            ],
        ),
        migrations.CreateModel(
            name='IntroductionKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=50, verbose_name='文章关键字列表')),
                ('titleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.IntroductionInfo')),
            ],
        ),
    ]
