# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-31 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=30, verbose_name='酒店名称')),
                ('locate', models.CharField(max_length=30, verbose_name='地理位置')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每晚价格')),
            ],
        ),
        migrations.CreateModel(
            name='HotelKeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelkeywords', models.CharField(max_length=30, verbose_name='关键字')),
                ('hotelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelInfo')),
            ],
        ),
    ]
